PolicyEngine/policyengine-uk-data

policyengine_uk_data/datasets/frs/enhanced_frs.py, policyengine_uk_data/utils/imputations/capital_gains.py
Increases early stopping and also makes sure we don't error when building the enhanced FRS without the extended FRS already built.
=> Adjust imputation behaviour

CHANGELOG.md, changelog.yaml, policyengine_uk_data/datasets/__init__.py, policyengine_uk_data/datasets/spi.py, policyengine_uk_data/utils/imputations/capital_gains.py, policyengine_uk_data/utils/loss.py, pyproject.toml
This adds fixes needed to integrate with the UK package.
=> Make compatible with policyengine-uk

CHANGELOG.md, changelog.yaml, policyengine_uk_data/datasets/frs/enhanced_frs.py, policyengine_uk_data/datasets/frs/extended_frs.py, policyengine_uk_data/datasets/frs/frs.py, pyproject.toml
These previously generated an error with PolicyEngine UK.
=> Fix data download URLs

CHANGELOG.md, changelog.yaml, policyengine_uk_data/utils/imputations/consumption.py, policyengine_uk_data/utils/imputations/income.py, policyengine_uk_data/utils/imputations/vat.py, policyengine_uk_data/utils/imputations/wealth.py, pyproject.toml
This means that packages that import uk-data don't need SE.
=> Move Survey-Enhance to not a top-level import

.github/workflows/ci_cd.yaml, CHANGELOG.md, changelog.yaml, policyengine_uk_data/datasets/frs/enhanced_frs.py, policyengine_uk_data/datasets/frs/extended_frs.py, policyengine_uk_data/datasets/frs/frs.py, policyengine_uk_data/utils/imputations/capital_gains.py, policyengine_uk_data/utils/imputations/wealth.py, pyproject.toml
=> Fix Decapitalise 'Upload Data' in action #17

CHANGELOG.md, changelog.yaml, policyengine_uk_data/datasets/frs/enhanced_frs.py, policyengine_uk_data/datasets/frs/frs.py, pyproject.toml
=> Fix bug removing capital gains

CHANGELOG.md, changelog.yaml, policyengine_uk_data/datasets/frs/local_areas/constituencies/calibrate.py, pyproject.toml
=> Sort constituency weights

changelog_entry.yaml, docs/validation/constituencies.ipynb, docs/validation/local_authorities.ipynb, policyengine_uk_data/datasets/frs/local_areas/constituencies/calibrate.py, policyengine_uk_data/datasets/frs/local_areas/constituencies/loss.py, policyengine_uk_data/datasets/frs/local_areas/local_authorities/calibrate.py, policyengine_uk_data/datasets/frs/local_areas/local_authorities/loss.py, policyengine_uk_data/storage/local_authorities_2021.csv
=> Make local area weights respect households' countries

changelog_entry.yaml, policyengine_uk_data/datasets/frs/enhanced_frs.py, policyengine_uk_data/datasets/frs/frs.py
=> Set disability inferred from benefit takeup

Makefile, policyengine_uk_data/datasets/frs/local_areas/constituencies/calibrate.py, policyengine_uk_data/datasets/frs/local_areas/local_authorities/calibrate.py, policyengine_uk_data/datasets/frs/local_areas/local_authorities/loss.py, policyengine_uk_data/utils/imputations/public_services.py
=> Add holdout analysis

changelog_entry.yaml, policyengine_uk_data/utils/loss.py
=> Add North West England calibration

changelog_entry.yaml, policyengine_uk_data/datasets/frs/childcare/takeup_rate.py, policyengine_uk_data/datasets/frs/enhanced_frs.py, policyengine_uk_data/datasets/frs/frs.py, policyengine_uk_data/tests/test_childcare.py
=> Add childcare spending and caseload tests

Makefile, changelog_entry.yaml, policyengine_uk_data/datasets/frs/local_areas/constituencies/calibrate.py, policyengine_uk_data/tests/test_child_limit.py, policyengine_uk_data/utils/loss.py
=> Re-add child limit affected household targets

.github/workflows/push.yaml, changelog_entry.yaml
=> Documentation fails to deploy

.github/workflows/pull_request.yaml, .github/workflows/push.yaml, changelog_entry.yaml
=> Add training log to build artifacts

.github/workflows/pull_request.yaml, .github/workflows/push.yaml, changelog_entry.yaml, policyengine_uk_data/datasets/frs/local_areas/constituencies/calibrate.py, policyengine_uk_data/datasets/frs/local_areas/constituencies/loss.py, policyengine_uk_data/datasets/frs/local_areas/local_authorities/loss.py
=> Local employment income targets do not sum to nationals

changelog_entry.yaml, policyengine_uk_data/utils/loss.py
=> Add calibration of PIP standard and enhanced claimants

changelog_entry.yaml, policyengine_uk_data/datasets/frs/frs.py, policyengine_uk_data/tests/test_aggregates.py
=> Add free school meals

docs/index.yaml
Reverts PolicyEngine/policyengine-uk-data#181
=> Revert "Add index file in doc folder"

changelog_entry.yaml, policyengine_uk_data/utils/qrf.py
We were using the wrong syntax for the latest version of microimpute.
=> Fix issue in imputation model
